version: "3.8"

services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      #ports=HOST:CONTAINER
      - "32000:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    ports:
      #ports=HOST:CONTAINER
      - "32001:8080"
    env_file: .env
    links:
      - db
    depends_on:
      - "db"