dbt_project:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "db"
      # IMPORTANT: Make sure to quote the entire Jinja string here
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_ADMIN_PASSWORD') }}"
      port: 32000
      dbname: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"